### ISSUE TITLE
cifar10

### ISSUE THREAD

**Issue by wm901115nwpu** [SsnL/dataset-distillation#1]
TypeError: __init__() got an unexpected keyword argument 'padding_mode'.
How to deal with it?

**Comment by SsnL** [comment]
Could you post the command you use and the stack trace?

**Comment by wm901115nwpu** [comment]
python3 main.py --mode distill_basic --dataset Cifar10 --arch AlexCifarNet


2019-01-07 15:41:13 [WARNING]  ./results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)/opt.yaml already exists, moved to ./results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)/old_opts/opt_2019_01_07__09_52_53.yaml
2019-01-07 15:41:13 [ERROR]  Fatal error:
2019-01-07 15:41:13 [ERROR]  Traceback (most recent call last):
2019-01-07 15:41:13 [ERROR]    File "main.py", line 401, in <module>
2019-01-07 15:41:13 [ERROR]      main(options.get_state())
2019-01-07 15:41:13 [ERROR]    File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
2019-01-07 15:41:13 [ERROR]      return self.set_state(self.state)
2019-01-07 15:41:13 [ERROR]    File "/home/wangmeng/dataset-distillation/base_options.py", line 517, in set_state
2019-01-07 15:41:13 [ERROR]      train_dataset = datasets.get_dataset(state, 'train')
2019-01-07 15:41:13 [ERROR]    File "/home/wangmeng/dataset-distillation/datasets/__init__.py", line 142, in get_dataset
2019-01-07 15:41:13 [ERROR]      transforms.RandomCrop(input_size, padding=4, padding_mode='reflect'),
2019-01-07 15:41:13 [ERROR]  TypeError: __init__() got an unexpected keyword argument 'padding_mode'
Traceback (most recent call last):
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 517, in set_state
    train_dataset = datasets.get_dataset(state, 'train')
  File "/home/wangmeng/dataset-distillation/datasets/__init__.py", line 142, in get_dataset
    transforms.RandomCrop(input_size, padding=4, padding_mode='reflect'),
TypeError: __init__() got an unexpected keyword argument 'padding_mode'

**Comment by SsnL** [comment]
@wm901115nwpu Make sure that you have torchvision 0.2.1.

**Comment by wm901115nwpu** [comment]
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
>>> print(torchvision.__version__)
0.2.1
>>>

**Comment by SsnL** [comment]
Oh I realized the problem. The argument is added after 0.2.1. You can work around it by installing from https://github.com/pytorch/vision. I'll find a better solution soon.

**Comment by wm901115nwpu** [comment]
INFO:root:Logging to ./results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)/output.log
WARNING:root:Log file already exists, will append
--- Logging error ---
Traceback (most recent call last):
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 15, in emit
    tqdm.tqdm.write(msg)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 525, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
Call stack:
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 402, in set_state
    logging.info("=" * 40 + " " + state.opt.start_time + " " + "=" * 40)
  File "/usr/lib/python3.5/logging/__init__.py", line 1838, in info
    root.info(msg, *args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1279, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 20, in emit
    self.handleError(record)
Message: '======================================== 2019-01-07 20:57:52 ========================================'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 15, in emit
    tqdm.tqdm.write(msg)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 525, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
Call stack:
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 403, in set_state
    logging.info('Base directory is {}'.format(base_dir))
  File "/usr/lib/python3.5/logging/__init__.py", line 1838, in info
    root.info(msg, *args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1279, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 20, in emit
    self.handleError(record)
Message: 'Base directory is ./results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 15, in emit
    tqdm.tqdm.write(msg)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 525, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
Call stack:
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 413, in set_state
    logging.info("Options:\n\t" + yaml_str.replace("\n", "\n\t"))
  File "/usr/lib/python3.5/logging/__init__.py", line 1838, in info
    root.info(msg, *args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1279, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 20, in emit
    self.handleError(record)
Message: "Options:\n\tarch: AlexCifarNet\n\tattack_class: 0\n\tbase_seed: 1\n\tbatch_size: 1024\n\tcheckpoint_interval: 10\n\tdataset: Cifar10\n\tdataset_labels: !!python/tuple\n\t- plane\n\t- car\n\t- bird\n\t- cat\n\t- deer\n\t- dog\n\t- monkey\n\t- horse\n\t- ship\n\t- truck\n\tdataset_normalization: !!python/tuple\n\t- !!python/tuple\n\t    - 0.4914\n\t    - 0.4822\n\t    - 0.4465\n\t- !!python/tuple\n\t    - 0.247\n\t    - 0.243\n\t    - 0.261\n\tdataset_root: ./data/cifar10\n\tdecay_epochs: 50\n\tdecay_factor: 0.5\n\tdevice_id: 0\n\tdistill_epochs: 3\n\tdistill_lr: 0.001\n\tdistill_steps: 10\n\tdistilled_images_per_class_per_step: 1\n\tdistributed: false\n\tdropout: false\n\tepochs: 200\n\texpr_name_format: null\n\timage_dpi: 80\n\tinit: xavier\n\tinit_param: 1.0\n\tinput_size: 32\n\tlog_file: ./results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)/output.log\n\tlog_interval: 100\n\tlog_level: INFO\n\tlr: 0.01\n\tmode: distill_basic\n\tmodel_dir: ./models/\n\tmodel_subdir_format: null\n\tn_nets: 1\n\tnc: 3\n\tno_log: false\n\tnum_classes: 10\n\tnum_workers: 8\n\tphase: train\n\tresults_dir: ./results/\n\tsample_n_nets: 1\n\tsource_dataset: null\n\tstart_time: '2019-01-07 20:57:52'\n\ttarget_class: 1\n\ttest_batch_size: 1024\n\ttest_distill_epochs: null\n\ttest_distilled_images: loaded\n\ttest_distilled_lrs:\n\t- loaded\n\ttest_n_nets: 1\n\ttest_n_runs: 1\n\ttest_name_format: null\n\ttest_nets_type: unknown_init\n\ttest_niter: 1\n\ttest_optimize_n_nets: 20\n\ttest_optimize_n_runs: null\n\ttrain_nets_type: unknown_init\n\tworld_rank: 0\n\tworld_size: 1\n\t"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 15, in emit
    tqdm.tqdm.write(msg)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 525, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
Call stack:
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 431, in set_state
    logging.warning('{} already exists, moved to {}'.format(yaml_name, old_opt_new_name))
  File "/usr/lib/python3.5/logging/__init__.py", line 1823, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1291, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 20, in emit
    self.handleError(record)
Message: './results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)/opt.yaml already exists, moved to ./results/distill_basic/Cifar10/arch(AlexCifarNet,xavier,1.0)_distillLR0.001_E(200,50,0.5)_lr0.01_B1x10x3_train(unknown_init)/old_opts/opt_2019_01_07__20_55_26.yaml'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 517, in set_state
    train_dataset = datasets.get_dataset(state, 'train')
  File "/home/wangmeng/dataset-distillation/datasets/__init__.py", line 142, in get_dataset
    transforms.RandomCrop(input_size, padding=4, padding_mode='reflect'),
TypeError: __init__() got an unexpected keyword argument 'padding_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 15, in emit
    tqdm.tqdm.write(msg)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 525, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
Call stack:
  File "main.py", line 403, in <module>
    logging.exception("Fatal error:")
  File "/usr/lib/python3.5/logging/__init__.py", line 1813, in exception
    error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1805, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/wangmeng/dataset-distillation/utils/logging.py", line 20, in emit
    self.handleError(record)
Message: 'Fatal error:'
Arguments: ()
Traceback (most recent call last):
  File "main.py", line 401, in <module>
    main(options.get_state())
  File "/home/wangmeng/dataset-distillation/base_options.py", line 341, in get_state
    return self.set_state(self.state)
  File "/home/wangmeng/dataset-distillation/base_options.py", line 517, in set_state
    train_dataset = datasets.get_dataset(state, 'train')
  File "/home/wangmeng/dataset-distillation/datasets/__init__.py", line 142, in get_dataset
    transforms.RandomCrop(input_size, padding=4, padding_mode='reflect'),
TypeError: __init__() got an unexpected keyword argument 'padding_mode'

**Comment by SsnL** [comment]
did you uninstall the old torchvision?

**Comment by SsnL** [comment]
what's your tqdm version btw?

**Comment by wm901115nwpu** [comment]
I uninstall torchvision and reinstall torchvision.
>>> import tqdm
>>> print(tqdm.__version__)
4.29.0

**Comment by SsnL** [comment]
If you installed torchvision from source, it should not give you `TypeError: init() got an unexpected keyword argument 'padding_mode'` error.

**Comment by SsnL** [comment]
@wm901115nwpu I also just pushed a new commit that should fix this. Could you pull and try again?

**Comment by wm901115nwpu** [comment]
I uninstall torchvision and I reinstall torchvision from source, It can run.

**Comment by SsnL** [comment]
The tqdm error puzzles me though, as your version should include the fix for a seemingly same bug reported at https://github.com/pytorch/vision/issues/488. It also didn't happen in the first output segment you posted....

**Comment by SsnL** [comment]
@wm901115nwpu Glad to know it is working for you! I'm closing this for now then.
