### ISSUE TITLE
Loss becomes NaN

### ISSUE THREAD

**Issue by ilia10000** [SsnL/dataset-distillation#11]
When I run the unknown initialization experiments on MNIST: 
`python main.py --mode distill_basic --dataset MNIST --arch LeNet`
I get the following after a few dozen epochs:
`Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main(options.get_state())
  File "main.py", line 130, in main
    steps = train_distilled_image.distill(state, state.models)
  File "/home/isucholu/original/dataset-distillation/train_distilled_image.py", line 296, in distill
    return Trainer(state, models).train()
  File "/home/isucholu/original/dataset-distillation/train_distilled_image.py", line 283, in train
    raise RuntimeError('loss became NaN')
RuntimeError: loss became NaN`
Was gradient fairly stable when you were running this for the paper? Do I just need to make some more attempts?

**Comment by SsnL** [comment]
That is weird. In my experience it has been quite stable. Maybe try with a lower learning rate?

**Comment by ilia10000** [comment]
Yeah looks like lower learning rate leads to more stable gradients. It might be the updated default learning rate you set the other day is too high for this mode?

**Comment by SsnL** [comment]
@ilia10000 Ah yeah it could be. I reset it back to 0.01 in https://github.com/SsnL/dataset-distillation/commit/00652bb94596addf8ddda2f89cae8aaac6b21747 just to be safe. Let me know if it still is unstable for you.

**Comment by Rubiel1** [comment]
Question: how do I interpret the nan on the standard deviation?  can this be related to @ilia10000  learning rate problem?
```
2020-11-29 07:15:24 [INFO ]  distilled with 10 steps and 3 epochs  (1 unknown_init nets) test results: 
2020-11-29 07:15:24 [INFO ]  	          STEP                   ACCURACY                   LOSS          
2020-11-29 07:15:24 [INFO ]  	            before steps          28.7854 ±  nan%            1.1057 ±  nan
2020-11-29 07:15:24 [INFO ]  	     step 30 (lr=0.0121)          38.1032 ±  nan%            1.0879 ±  nan
```

**Comment by ilia10000** [comment]
@Rubiel1 You're using a single unknown init net, so there is only a single result (i.e. just the one accuracy value). If you use more nets you'll have standard deviations.
