### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by shraddha291996** [ssnl/dataset-distillation#58]
Hello, 

I am using AlexNet and custom dataset with rgb images , I am cropping them to 32 by 32 size. AndI get the following error. Could you please help me with this issue? 

python main.py --mode distill_basic --dataset data_custom --arch LeNet     --distill_lr 0.001
INFO:root:Logging to ./results/distill_basic/data_custom/arch(LeNet,xavier,1.0)_distillLR0.001_E(400,40,0.5)_lr0.01_B1x10x3_train(unknown_init)/output.log
WARNING:root:Log file already exists, will append
2022-12-28 16:12:46 [INFO ]  ======================================== 2022-12-28 16:12:46 ========================================
2022-12-28 16:12:46 [INFO ]  Base directory is ./results/distill_basic/data_custom/arch(LeNet,xavier,1.0)_distillLR0.001_E(400,40,0.5)_lr0.01_B1x10x3_train(unknown_init)
2022-12-28 16:12:46 [INFO ]  Options:
2022-12-28 16:12:46 [INFO ]     arch: LeNet
2022-12-28 16:12:46 [INFO ]     attack_class: 0
2022-12-28 16:12:46 [INFO ]     base_seed: 1
2022-12-28 16:12:46 [INFO ]     batch_size: 1024
2022-12-28 16:12:46 [INFO ]     checkpoint_interval: 10
2022-12-28 16:12:46 [INFO ]     dataset: data_custom
2022-12-28 16:12:46 [INFO ]     dataset_labels: !!python/tuple
2022-12-28 16:12:46 [INFO ]     - class1
2022-12-28 16:12:46 [INFO ]     - class2
2022-12-28 16:12:46 [INFO ]     - class3
2022-12-28 16:12:46 [INFO ]     - class4
2022-12-28 16:12:46 [INFO ]     dataset_normalization: !!python/tuple
2022-12-28 16:12:46 [INFO ]     - !!python/tuple
2022-12-28 16:12:46 [INFO ]         - 0.47850531339645386
2022-12-28 16:12:46 [INFO ]         - 0.4992702007293701
2022-12-28 16:12:46 [INFO ]         - 0.4022205173969269
2022-12-28 16:12:46 [INFO ]     - !!python/tuple
2022-12-28 16:12:46 [INFO ]         - 0.23210887610912323
2022-12-28 16:12:46 [INFO ]         - 0.2277066558599472
2022-12-28 16:12:46 [INFO ]         - 0.26652416586875916
2022-12-28 16:12:46 [INFO ]     dataset_root: /home/wgs.wuerth.com/la00204104/dataset-distillation/data/dataset
2022-12-28 16:12:46 [INFO ]     decay_epochs: 40
2022-12-28 16:12:46 [INFO ]     decay_factor: 0.5
2022-12-28 16:12:46 [INFO ]     device_id: 0
2022-12-28 16:12:46 [INFO ]     distill_epochs: 3
2022-12-28 16:12:46 [INFO ]     distill_lr: 0.001
2022-12-28 16:12:46 [INFO ]     distill_steps: 10
2022-12-28 16:12:46 [INFO ]     distilled_images_per_class_per_step: 1
2022-12-28 16:12:46 [INFO ]     distributed: false
2022-12-28 16:12:46 [INFO ]     dropout: false
2022-12-28 16:12:46 [INFO ]     epochs: 400
2022-12-28 16:12:46 [INFO ]     expr_name_format: null
2022-12-28 16:12:46 [INFO ]     image_dpi: 80
2022-12-28 16:12:46 [INFO ]     init: xavier
2022-12-28 16:12:46 [INFO ]     init_param: 1.0
2022-12-28 16:12:46 [INFO ]     input_size: 32
2022-12-28 16:12:46 [INFO ]     log_file: ./results/distill_basic/data_custom/arch(LeNet,xavier,1.0)_distillLR0.001_E(400,40,0.5)_lr0.01_B1x10x3_train(unknown_init)/output.log
2022-12-28 16:12:46 [INFO ]     log_interval: 100
2022-12-28 16:12:46 [INFO ]     log_level: INFO
2022-12-28 16:12:46 [INFO ]     lr: 0.01
2022-12-28 16:12:46 [INFO ]     mode: distill_basic
2022-12-28 16:12:46 [INFO ]     model_dir: ./models/
2022-12-28 16:12:46 [INFO ]     model_subdir_format: null
2022-12-28 16:12:46 [INFO ]     n_nets: 1
2022-12-28 16:12:46 [INFO ]     nc: 3
2022-12-28 16:12:46 [INFO ]     no_log: false
2022-12-28 16:12:46 [INFO ]     num_classes: 4
2022-12-28 16:12:46 [INFO ]     num_workers: 8
2022-12-28 16:12:46 [INFO ]     phase: train
2022-12-28 16:12:46 [INFO ]     results_dir: ./results/
2022-12-28 16:12:46 [INFO ]     sample_n_nets: 1
2022-12-28 16:12:46 [INFO ]     source_dataset: null
2022-12-28 16:12:46 [INFO ]     start_time: '2022-12-28 16:12:46'
2022-12-28 16:12:46 [INFO ]     target_class: 1
2022-12-28 16:12:46 [INFO ]     test_batch_size: 1024
2022-12-28 16:12:46 [INFO ]     test_distill_epochs: null
2022-12-28 16:12:46 [INFO ]     test_distilled_images: loaded
2022-12-28 16:12:46 [INFO ]     test_distilled_lrs:
2022-12-28 16:12:46 [INFO ]     - loaded
2022-12-28 16:12:46 [INFO ]     test_n_nets: 1
2022-12-28 16:12:46 [INFO ]     test_n_runs: 1
2022-12-28 16:12:46 [INFO ]     test_name_format: null
2022-12-28 16:12:46 [INFO ]     test_nets_type: unknown_init
2022-12-28 16:12:46 [INFO ]     test_niter: 1
2022-12-28 16:12:46 [INFO ]     test_optimize_n_nets: 20
2022-12-28 16:12:46 [INFO ]     test_optimize_n_runs: null
2022-12-28 16:12:46 [INFO ]     train_nets_type: unknown_init
2022-12-28 16:12:46 [INFO ]     world_rank: 0
2022-12-28 16:12:46 [INFO ]     world_size: 1
2022-12-28 16:12:46 [INFO ]
2022-12-28 16:12:46 [WARNING]  ./results/distill_basic/data_custom/arch(LeNet,xavier,1.0)_distillLR0.001_E(400,40,0.5)_lr0.01_B1x10x3_train(unknown_init)/opt.yaml already exists, moved to ./results/distill_basic/data_custom/arch(LeNet,xavier,1.0)_distillLR0.001_E(400,40,0.5)_lr0.01_B1x10x3_train(unknown_init)/old_opts/opt_2022_12_28__16_03_51.yaml
2022-12-28 16:12:57 [INFO ]  train dataset size:        50000
2022-12-28 16:12:57 [INFO ]  test dataset size:         10000
2022-12-28 16:12:57 [INFO ]  datasets built!
2022-12-28 16:12:57 [INFO ]  mode: distill_basic, phase: train
2022-12-28 16:12:57 [INFO ]  Build 1 LeNet network(s) with [xavier(1.0)] init
2022-12-28 16:13:00 [INFO ]  Build 1 LeNet network(s) with [xavier(1.0)] init
2022-12-28 16:13:00 [INFO ]  Train 10 steps iterated for 3 epochs
/home/wgs.wuerth.com/la00204104/anaconda3/envs/distil/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
2022-12-28 16:13:01 [INFO ]  Results saved to ./results/distill_basic/data_custom/arch(LeNet,xavier,1.0)_distillLR0.001_E(400,40,0.5)_lr0.01_B1x10x3_train(unknown_init)/checkpoints/epoch0000/results.pth
2022-12-28 16:13:01 [INFO ]
2022-12-28 16:13:01 [INFO ]  Begin of epoch 0 :
Begin of epoch 0 (1 unknown_init nets):   0%|                                                                                                                                                                          | 0/2 [00:00<?, ?it/s]/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1616554827596/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
2022-12-28 16:13:02 [ERROR]  Fatal error:
2022-12-28 16:13:02 [ERROR]  Traceback (most recent call last):
2022-12-28 16:13:02 [ERROR]    File "main.py", line 402, in <module>
2022-12-28 16:13:02 [ERROR]      main(options.get_state())
2022-12-28 16:13:02 [ERROR]    File "main.py", line 131, in main
2022-12-28 16:13:02 [ERROR]      steps = train_distilled_image.distill(state, state.models)
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/train_distilled_image.py", line 290, in distill
2022-12-28 16:13:02 [ERROR]      return Trainer(state, models).train()
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/train_distilled_image.py", line 221, in train
2022-12-28 16:13:02 [ERROR]      evaluate_steps(state, steps, 'Begin of epoch {}'.format(epoch))
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 288, in evaluate_steps
2022-12-28 16:13:02 [ERROR]      res = _evaluate_steps(test_nets_desc, reset=(state.test_nets_type == 'unknown_init'))
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 276, in _evaluate_steps
2022-12-28 16:13:02 [ERROR]      params = train_steps_inplace(state, models, steps, params, callback=test_callback)
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 65, in train_steps_inplace
2022-12-28 16:13:02 [ERROR]      callback(i, params)
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 268, in test_callback
2022-12-28 16:13:02 [ERROR]      test_loader_iter=test_loader_iter)
2022-12-28 16:13:02 [ERROR]    File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 138, in evaluate_models
2022-12-28 16:13:02 [ERROR]      losses[k] += task_loss(state, output, target, reduction='sum').item()  # sum up batch loss
2022-12-28 16:13:02 [ERROR]  RuntimeError: CUDA error: device-side assert triggered
Begin of epoch 0 (1 unknown_init nets):   0%|                                                                                                                                                                          | 0/2 [00:01<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main(options.get_state())
  File "main.py", line 131, in main
    steps = train_distilled_image.distill(state, state.models)
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/train_distilled_image.py", line 290, in distill
    return Trainer(state, models).train()
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/train_distilled_image.py", line 221, in train
    evaluate_steps(state, steps, 'Begin of epoch {}'.format(epoch))
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 288, in evaluate_steps
    res = _evaluate_steps(test_nets_desc, reset=(state.test_nets_type == 'unknown_init'))
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 276, in _evaluate_steps
    params = train_steps_inplace(state, models, steps, params, callback=test_callback)
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 65, in train_steps_inplace
    callback(i, params)
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 268, in test_callback
    test_loader_iter=test_loader_iter)
  File "/home/wgs.wuerth.com/la00204104/dataset-distillation/basics.py", line 138, in evaluate_models
    losses[k] += task_loss(state, output, target, reduction='sum').item()  # sum up batch loss
RuntimeError: CUDA error: device-side assert triggered
Begin of epoch 0 (1 unknown_init nets):   0%|                                                                             

Thanks in advance

**Comment by ssnl** [comment]
> Assertion t >= 0 && t < n_classes failed

The error message tells you that your class index is set wrongly
